import type { JobCategory } from "./jobQuestions";

export type OpportunityJob = {
  id: string;
  company: string;
  role: string;
  location: string;
  type: "Full Time" | "Internship" | "Contract";
  workMode: "Remote" | "Hybrid" | "Onsite";
  category: JobCategory;
  salaryMin: number;
  salaryMax: number;
  match: number;
  recommendedProgram: string;
  matchedSkills: string[];
  skillGaps: string[];
  logo: string;
  color: string;
  isSample: boolean;
};

const companies = [
  "Northstar Labs",
  "Vertex Systems",
  "CloudAxis",
  "Nexa Digital",
  "BrightLayer AI",
  "Quantum Stack",
  "BlueOrbit Tech",
  "AstraCore",
  "NovaGrid",
  "Synthex Labs",
  "DataForge",
  "CyberNest",
  "CoreBridge",
  "TechVista",
  "Pioneer Cloud",
  "FutureMesh",
  "Elevate Systems",
  "LogicWave",
  "IronPeak Security",
  "PixelRoute",
  "OmniScale",
  "Skyline Digital",
  "CodeHarbor",
  "NeuralSpring",
  "SecureSphere",
  "CloudMint",
  "InnovaWorks",
  "PrimeStack",
  "DigitalCraft",
  "AtlasByte",
  "VisionGrid",
  "TrustLayer",
  "BluePeak",
  "DataNova",
  "CloudPilot",
  "DevOrbit",
  "RiskCanvas",
  "ByteBridge",
  "TechNova",
];

const roleTemplates = [
  {
    role: "AI Engineer",
    category: "AI & Data" as JobCategory,
    location: "Global",
    salaryMin: 150,
    salaryMax: 240,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["Python", "Machine Learning", "APIs"],
    skillGaps: ["Cloud Deployment", "System Design"],
    logo: "AI",
    color: "bg-cyan-600",
  },
  {
    role: "Data Scientist",
    category: "AI & Data" as JobCategory,
    location: "New York, USA",
    salaryMin: 135,
    salaryMax: 220,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["Python", "SQL", "Statistics"],
    skillGaps: ["Experiment Design", "Model Deployment"],
    logo: "DS",
    color: "bg-blue-600",
  },
  {
    role: "Machine Learning Engineer",
    category: "AI & Data" as JobCategory,
    location: "San Francisco, USA",
    salaryMin: 175,
    salaryMax: 280,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["Python", "ML Models", "Docker"],
    skillGaps: ["Kubernetes", "MLOps"],
    logo: "ML",
    color: "bg-indigo-600",
  },
  {
    role: "Generative AI Developer",
    category: "AI & Data" as JobCategory,
    location: "Global",
    salaryMin: 160,
    salaryMax: 260,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["Python", "LLMs", "Prompt Engineering"],
    skillGaps: ["RAG", "AI Evaluation"],
    logo: "GA",
    color: "bg-violet-600",
  },
  {
    role: "Data Analyst",
    category: "AI & Data" as JobCategory,
    location: "Austin, USA",
    salaryMin: 120,
    salaryMax: 175,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["SQL", "Excel", "Dashboards"],
    skillGaps: ["Python", "Statistics"],
    logo: "DA",
    color: "bg-sky-600",
  },
  {
    role: "Data Engineer",
    category: "AI & Data" as JobCategory,
    location: "Chicago, USA",
    salaryMin: 145,
    salaryMax: 230,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["SQL", "ETL", "Python"],
    skillGaps: ["Spark", "Data Architecture"],
    logo: "DE",
    color: "bg-teal-600",
  },
  {
    role: "AI Product Engineer",
    category: "AI & Data" as JobCategory,
    location: "Remote",
    salaryMin: 155,
    salaryMax: 245,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["AI APIs", "Product Thinking", "Python"],
    skillGaps: ["MLOps", "System Design"],
    logo: "AP",
    color: "bg-fuchsia-600",
  },
  {
    role: "NLP Engineer",
    category: "AI & Data" as JobCategory,
    location: "Boston, USA",
    salaryMin: 165,
    salaryMax: 270,
    recommendedProgram: "Data Science & AI",
    matchedSkills: ["NLP", "Python", "Transformers"],
    skillGaps: ["Model Serving", "Evaluation"],
    logo: "NL",
    color: "bg-purple-600",
  },
  {
    role: "Cyber Security Analyst",
    category: "Cyber Security" as JobCategory,
    location: "Global",
    salaryMin: 125,
    salaryMax: 195,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["Linux", "Networking", "SIEM"],
    skillGaps: ["Incident Response", "Threat Hunting"],
    logo: "CS",
    color: "bg-emerald-600",
  },
  {
    role: "SOC Analyst",
    category: "Cyber Security" as JobCategory,
    location: "Chicago, USA",
    salaryMin: 120,
    salaryMax: 180,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["SIEM", "Log Analysis", "Networking"],
    skillGaps: ["Detection Rules", "Investigation"],
    logo: "SOC",
    color: "bg-teal-600",
  },
  {
    role: "Cloud Security Engineer",
    category: "Cyber Security" as JobCategory,
    location: "Seattle, USA",
    salaryMin: 160,
    salaryMax: 260,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["Cloud", "IAM", "Networking"],
    skillGaps: ["Cloud Architecture", "DevSecOps"],
    logo: "CL",
    color: "bg-blue-700",
  },
  {
    role: "Penetration Tester",
    category: "Cyber Security" as JobCategory,
    location: "Boston, USA",
    salaryMin: 130,
    salaryMax: 210,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["Burp Suite", "Nmap", "Linux"],
    skillGaps: ["Web Exploitation", "Reporting"],
    logo: "PT",
    color: "bg-red-600",
  },
  {
    role: "Security Engineer",
    category: "Cyber Security" as JobCategory,
    location: "Denver, USA",
    salaryMin: 150,
    salaryMax: 235,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["Firewalls", "Linux", "Networking"],
    skillGaps: ["Cloud Security", "Automation"],
    logo: "SE",
    color: "bg-orange-600",
  },
  {
    role: "Threat Intelligence Analyst",
    category: "Cyber Security" as JobCategory,
    location: "Washington, USA",
    salaryMin: 135,
    salaryMax: 215,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["Threat Research", "OSINT", "Analysis"],
    skillGaps: ["Threat Modeling", "Automation"],
    logo: "TI",
    color: "bg-rose-600",
  },
  {
    role: "Security Operations Manager",
    category: "Cyber Security" as JobCategory,
    location: "Dallas, USA",
    salaryMin: 190,
    salaryMax: 300,
    recommendedProgram: "Cyber Security Program",
    matchedSkills: ["SOC", "Incident Response", "Leadership"],
    skillGaps: ["Threat Intelligence", "Cloud Security"],
    logo: "SM",
    color: "bg-red-700",
  },
  {
    role: "Cloud Engineer",
    category: "Engineering" as JobCategory,
    location: "Seattle, USA",
    salaryMin: 145,
    salaryMax: 230,
    recommendedProgram: "Cloud Engineering Program",
    matchedSkills: ["AWS", "Linux", "Networking"],
    skillGaps: ["Terraform", "Kubernetes"],
    logo: "CE",
    color: "bg-orange-500",
  },
  {
    role: "Backend Engineer",
    category: "Engineering" as JobCategory,
    location: "Global",
    salaryMin: 140,
    salaryMax: 220,
    recommendedProgram: "Software Engineering Program",
    matchedSkills: ["Node.js", "APIs", "Databases"],
    skillGaps: ["System Design", "Scaling"],
    logo: "BE",
    color: "bg-slate-700",
  },
  {
    role: "Full Stack Developer",
    category: "Engineering" as JobCategory,
    location: "Austin, USA",
    salaryMin: 130,
    salaryMax: 210,
    recommendedProgram: "Software Engineering Program",
    matchedSkills: ["React", "Node.js", "Git"],
    skillGaps: ["Testing", "Cloud Deployment"],
    logo: "FS",
    color: "bg-blue-500",
  },
  {
    role: "DevOps Engineer",
    category: "Engineering" as JobCategory,
    location: "Denver, USA",
    salaryMin: 155,
    salaryMax: 250,
    recommendedProgram: "Cloud Engineering Program",
    matchedSkills: ["Docker", "CI/CD", "Linux"],
    skillGaps: ["Kubernetes", "Infrastructure"],
    logo: "DO",
    color: "bg-violet-600",
  },
  {
    role: "Solutions Architect",
    category: "Engineering" as JobCategory,
    location: "Washington, USA",
    salaryMin: 210,
    salaryMax: 324,
    recommendedProgram: "Software Engineering Program",
    matchedSkills: ["Architecture", "Cloud", "APIs"],
    skillGaps: ["Distributed Systems", "Leadership"],
    logo: "SA",
    color: "bg-indigo-700",
  },
];

const workModes: OpportunityJob["workMode"][] = [
  "Remote",
  "Hybrid",
  "Onsite",
  "Remote",
];

const jobTypes: OpportunityJob["type"][] = [
  "Full Time",
  "Full Time",
  "Contract",
  "Internship",
];

export const opportunityJobs: OpportunityJob[] = Array.from(
  { length: 60 },
  (_, index) => {
    const company = companies[index % companies.length];
    const template = roleTemplates[index % roleTemplates.length];

    const mode = workModes[index % workModes.length];
    const type = jobTypes[index % jobTypes.length];

    const salaryIncrease = (index % 5) * 5;

    return {
      id: `opportunity-${index + 1}`,
      company,
      role: template.role,
      location:
        mode === "Remote" ? "Global Remote" : template.location,
      type,
      workMode: mode,
      category: template.category,
      salaryMin: template.salaryMin + salaryIncrease,
      salaryMax: template.salaryMax + salaryIncrease,
      match: 62 + ((index * 7) % 34),
      recommendedProgram: template.recommendedProgram,
      matchedSkills: template.matchedSkills,
      skillGaps: template.skillGaps,
      logo: template.logo,
      color: template.color,
      isSample: true,
    };
  },
);